#!/bin/bash
# Этот скрипт сбрасывает счётчик failcount ресурсов в corosync.
# Если значение failcount=1000000 у ресурса, то сбрасывается его состояние (crm resource cleanup <res>).
# 
# Это порой необходимо для очистки состояния кластера и вывода `crm_mon -fnr` после восстановленния кластера.
#
# Author: Ilia Sibiryatkin <Sibvilian@gmail.com>

NODE=`crm_node -l |cut -d' ' -f 2`

for RES in $(crm_mon -f1 |grep fail-count |awk '{ print $1}' |sort -u |awk '{print (substr($1,0,length($1)-1))}') ; do
	for i in $NODE ; do
		FAIL_VALUE=$(crm resource failcount $RES show $i |cut -d' ' -f4 |cut -d= -f2)
		if [[ $FAIL_VALUE == INFINITY ]]; then
			echo "cleanup $RES on $i"
			crm resource cleanup $RES $i
		else
			if [[ $FAIL_VALUE != 0 ]]; then
				echo "clear fail-count $RES on $i"
				crm resource failcount $RES delete $i
			fi
		fi
	done
done
