#!/bin/bash
#
# /opt/pmm-bms/sbin/rotate-j3-extra-logs /opt/just 2>&1>> /home/bms-backup/.engines-logs/log-rotate-just-extra.log
#

EngineDir=$1
EngineName=$(basename $EngineDir)
LogsDir=$EngineDir/log
ArcDir='/home/bms-backup/.engines-logs/J3-extra-logs'
HostName=$(hostname)
LogFile=$(dirname $ArcDir)'/log-rotate-'${EngineName}'-extra.log'
MaxLogFStr='1024'
MaxLogSize=$((1024*1024*1024*10))       # 10 Gb
NumberFile=700

ActualDirName=$(date '+%Y-%m-%d')
Datetime=$(date '+%R')
#####################################################################
if [[ $(du "$LogsDir/$ActualDirName"| cut -f1) < $MaxLogSize ]]; then
        echo "start false: size $(du -h "$LogsDir/$ActualDirName"| cut -f1)"
        exit 0
else
        echo "start true: size $(du -h "$LogsDir/$ActualDirName"| cut -f1)"
fi
###################

if [ ! -d "$ArcDir" ]; then
        mkdir -p $ArcDir
fi

if [ -f "$LogFile" ]; then
        CurLogStrs=$(cat $LogFile | wc -l)
        if [ "$CurLogStrs" -gt "$MaxLogFStr" ]; then
                mv -f ${LogFile} ${LogFile}'.0'
        fi
else
        touch $LogFile
fi

echo "$ActualTime    Engine: $EngineName"
echo "$ActualTime EngineDir: $EngineDir"
echo "$ActualTime   LogsDir: $LogsDir"
echo "$ActualTime    ArcDir: $ArcDir"

find "$LogsDir/$ActualDirName" -type f -name "??????_[0-9]*.log" > /dev/shm/temp.$EngineName.1

local prev_start=
if [ -e "$ArcDir/$EngineName-on-$HostName-$ActualDirName-0.tar.gz" ]; then
        prev_start=$(ls -la "$ArcDir/$EngineName-on-$HostName-$ActualDirName-*" |wc -l)
else
        prev_start=0
fi

for i in $(seq $prev_start $(( $(cat /dev/shm/temp.$EngineName.1 |wc -l)/$NumberFile + $prev_start )) ) ; do
        log_files=$(head -n $NumberFile /dev/shm/temp.$EngineName.1)
        tar -czf "$ArcDir/$EngineName-on-$HostName-$ActualDirName-$i.tar.gz" $log_files
        rm -f $log_files
        sed "1,$NumberFile d" /dev/shm/temp.$EngineName.1 > /dev/shm/temp.$EngineName.2
        mv /dev/shm/temp.$EngineName.2 /dev/shm/temp.$EngineName.1
done

rm -f /dev/shm/temp.$EngineName.1

echo "$ActualTime End rotate J3 extra log"
echo "---------------------------------------------------------------"
